### ISSUE TITLE
Question and assistance in building wpesrc plugin?

### ISSUE THREAD

**Issue by TVforME** [dorftv/dove#17]
Hello @hatsch,

Question which you may be able to assist with.
Are you building the GStreamer wpesrc plugin? I'm led to believe Dove is a docker based, however, I'm wanting to build native on its own hardware working towards a compact headless build.

I've spent days trying to get the GStreamer WPEWebKit plugin and its main dependencies built from source.
Each reliant of so many dependencies its over 50..  to install on a fresh build.

[libwpe-1.0-1](https://packages.debian.org/sid/libwpe-1.0-1)
[libwpebackend-fdo-1.0-1](https://packages.debian.org/sid/libwpebackend-fdo-1.0-1)
[libwpewebkit-2.0-1](https://packages.debian.org/sid/libwpewebkit-2.0-1)

Are the main contributors each of their own having dependencies.

Is there a package available which has ALL the dependencies bundled?   gstreamer1.0-wpe doesn't seem to be a valid repo taken from the docker script. Am I missing something?

Do you have a script or have any info which can allow for a successfully building this plugin. Any information greatly appreciated.  I see many advantages in using wpe for overlays.

Somebody else has had similar issues  https://stackoverflow.com/questions/78371845/how-to-build-wpe-gstreamer-plugin-with-cerbero

**Comment by hatsch** [comment]
unfortunatly i cannot help you with this. for the moment i am fine with debian providing the necessary packages for wpe and gstreamer.
if you like to build it on your own you can have a look at this repo: https://github.com/restreamio/docker-gstreamer
They are building gstreamer and the bundled plugins from source for their docker images.

If you are successfull i will happily accept a MR with an updated docker image built from scratch.
